<?php
/********************************
* yca plugin for Context Management Framework
* version: 6.x-dev
* Author: Roger Soper
*
* Interacts with the CMF to output yca ad-serving script
*
*********************************/



/**
* Implementation of hook_global_settings_form
*
* - the form_alter has been removed
*/
function yca_plugin_global_settings_form() {
	$form = array();
	
	$form['yca_plugin_settings'] = array(
		'#type' => 'fieldset',
		'#title' => t('YCA Plugin Settings'),
	);
	$form['yca_plugin_settings']['yca_plugin_enabled'] = array(
		'#type' => 'checkbox',
		'#title' => t('Enabled'),
		'#default_value' => variable_get('yca_plugin_enabled', 0),
	);
	$form['yca_plugin_settings']['yca_interface'] = array(
		'#type' => 'textfield',
		'#title' => t('Yahoo Ads Ad Interface'),
		'#description' => t('The ad interface for YCA (http://cm.npc-morris.overture.com/js_1_0/).'),
		'#size' => 30,
		'#maxlength' => 180,
		'#default_value' => variable_get('yca_interface', ''),
	);
	$form['yca_plugin_settings']['yca_source'] = array(
		'#type' => 'textfield',
		'#title' => t('Yahoo Ads Ad Source'),
		'#description' => t('The ad source for YCA (npc_morris_floridatimesunion).'),
		'#size' => 30,
		'#maxlength' => 180,
		'#default_value' => variable_get('yca_source', ''),
	);
	$form['yca_plugin_settings']['yca_config'] = array(
		'#type' => 'textfield',
		'#title' => t('Yahoo Ad Config Number'),
		'#description' => t('Enter your Yahoo ad config number here.'),
		'#size' => 30,
		'#maxlength' => 80,
		'#default_value' => variable_get('yca_config', ''),
	);
	$form['yca_plugin_settings']['yca_url'] = array(
		'#type' => 'textfield',
		'#title' => t('Yahoo Ads JS URL'),
		'#description' => t('The URL that points to the Yahoo js.'),
		'#size' => 30,
		'#maxlength' => 180,
		'#default_value' => variable_get('yca_url', ''),
	);
	$form['yca_plugin_settings']['yca_css'] = array(
		'#type' => 'textfield',
		'#title' => t('Yahoo CSS URL'),
		'#description' => t('The path to the yahoo CSS.'),
		'#size' => 30,
		'#maxlength' => 180,
		'#default_value' => variable_get('yca_css', ''),
	);
		$form['yca_plugin_settings']['yca_def_type'] = array(
		'#type' => 'select',
		'#title' => t('YCA Default Ad Type'),
		'#default_value' => variable_get('yca_def_type', 'Other'),
		'#options' => yca_plugin_type_options(),
		'#description' => t('The default type for ads.'),
	);
	$form['yca_plugin_settings']['yca_def_tier'] = array(
		'#type' => 'select',
		'#title' => t('YCA Default Ad Tier'),
		'#default_value' => variable_get('yca_def_tier', '1'),
		'#options' => yca_plugin_tier_options(),
		'#description' => t('The default tier of the default type.'),
	);
	return $form;
}


/**
* Implementation of hook_mapping_settings_form
*
* @changed: term weight is now handled by the core module. 
*/
function yca_plugin_mapping_settings_form($default_values = NULL) {
	$form = array();
	
	$default_values = unserialize($default_values);
	$form['yca_plugin'] = array(
		'#type'  => 'fieldset',
		'#title' => t('YCA Plugin Settings'),
	);
	$form['yca_plugin']['yca_plugin_type'] = array(
		'#type' => 'select',
		'#title' => t('YCA Type'),
		'#default_value' => $default_values['yca_type'],
		'#options' => yca_plugin_type_options(),
		'#description' => t('The type of ad you want displayed.'),
	);
	$form['yca_plugin']['yca_plugin_tier'] = array(
		'#type' => 'select',
		'#title' => t('YCA Tier'),
		'#default_value' => $default_values['yca_tier'],
		'#options' => yca_plugin_tier_options(),
		'#description' => t('The tier of the YCA type.'),
	);

	return $form;
}

/**
* Implemtation of hook_mapping_settings_submit_handler()
* @return $adjusted_value a serialize array of plugin specific values
*/
function yca_plugin_mapping_settings_submit_handler($form_values) {
	$adjusted_value = serialize(array('yca_type' => $form_values['yca_plugin_type'], 'yca_tier' => $form_values['yca_plugin_tier']));
	return $adjusted_value;	
}

function yca_plugin_table_display_data($my_values) {
	$my_values = unserialize($my_values);
	$my_display = $my_values['yca_type'] . "  |  " . $my_values['yca_tier']	;
	
	return $my_display;
}

function yca_plugin_output($yca_values) {
	global $script_written;

	$yca_values = unserialize($yca_values);
	$yca_display = $yca_values['yca_type'] . "  |  " . $yca_values['yca_tier']	;
	
	// chcecking for a custom type set in the mapping settings
	$yca_type =  $yca_values['yca_type'];
	// if no custom type set then set to default in manager settings
	if(!$yca_type){
		$yca_type = variable_get('yca_def_type', '');
	}

	// chcecking for a custom tier set in the mapping settings
	$yca_tier =  $yca_values['yca_tier'];
	// if no custom tier set then set to default in manager settings
	if(!$yca_tier){
		$yca_tier = variable_get('yca_def_tier', '');
	}

	if (!$script_written['yca_plugin']) {
		$output = "
			<!-- YCA Variables Begin -->
			var yca_type = '" . $yca_type  . "';
			var yca_tier = '" . $yca_tier  . "';
			<!-- YCA Variables End -->
		";
		drupal_add_js($output, 'inline', 'header', FALSE, TRUE);
		$script_written['yca_plugin'] = TRUE;
	}
}


/**
*	implementation of hook_block()
*/
	
function yca_plugin_block($op = 'list', $delta = 0, $edit = array()) {
	
	// setting multi use variables
	$host  = $_SERVER['HTTP_HOST'];

	// chcecking for a custom path set in the manager settings
	$yahoo_css = variable_get('yca_css','');
	// if no custom path set then default to local copy
	if(!$yahoo_css){
		$yahoo_path_css = "/sites/all/modules/morris/casaa/plugins/yca_plugin/yahoo.css";
		$yahoo_css = "http://$host$yahoo_path_css";
	}

	// chcecking for a custom path set in the manager settings
	$yahoo_js = variable_get('yca_url','');
	// if no custom path set then default to local copy
	if(!$yahoo_js){
		$yahoo_path_js = "/sites/all/modules/morris/casaa/plugins/yca_plugin/yahoo.js";
		$yahoo_js = "http://$host$yahoo_path_js";
	}

	$yca_output_start = "
		<!-- YCA SETUP BEGINS -->
		<script type=\"text/javascript\">
			ctxt_ad_interface = '" . variable_get('yca_interface', '') . "';
			ctxt_ad_source = '" . variable_get('yca_source', '') . "_t' + yca_tier + '_ctxt';
			ctxt_ad_config = '" . variable_get('yca_config', '') . "';
			ctxt_ad_url = window.location.href;
	";
			
	$yca_output_end = "
			ctxt_ad_id = yca_type;
			ctxt_ad_type = yca_type;
			ctxt_ad_css = '$yahoo_css';
			ctxt_ad_bc = 'FFFFFF';
			ctxt_ad_bg = 'FFFFFF';
			ctxt_ad_newwin = 1;
		</script>
		<script src='$yahoo_js' type='text/javascript'></script>
		<!-- YCA SETUP END -->
	";
	  // The $op parameter determines what piece of information is being requested.
	  switch ($op) {
	    case 'list':
	      // If $op is "list", we just need to return a list of block descriptions.
	      // This is used to provide a list of possible blocks to the administrator,
	      // end users will not see these descriptions.
		$blocks[0]['info'] = t('YCA: Leaderboard 728x90 Block');
		$blocks[1]['info'] = t('YCA: Skyscraper 120x600 Block');
		$blocks[2]['info'] = t('YCA: Wide skyscraper 160x600 Block');
		$blocks[3]['info'] = t('YCA: Small rectangle 180x150 Block');
		$blocks[4]['info'] = t('YCA: Vertical banner 120x240 Block');
		$blocks[5]['info'] = t('YCA: Half-banner 234x60 Block');
		$blocks[6]['info'] = t('YCA: Banner 468x60 Block');
		$blocks[7]['info'] = t('YCA: Medium rectangle 300x250 Block');
		$blocks[8]['info'] = t('YCA: Square 250x250 Block');
		$blocks[9]['info'] = t('YCA: Large rectangle 336x280 Block');
		$blocks[10]['info'] = t('YCA: 420x150 Block');
		$blocks[11]['info'] = t('YCA: 240x400 Block');
		return $blocks;
	    case 'configure':
		  // If $op is "configure", we need to provide the administrator with a
	      // configuration form. The $delta parameter tells us which block is being
	      // configured. 
	      $form = array();
	      return $form;
	    case 'save':
	      // If $op is "save", we need to save settings from the configuration form.
	      return;
	    case 'view': default:
	      // If $op is "view", then we need to generate the block for display
	      // purposes. The $delta parameter tells us which block is being requested.
	      switch ($delta) {
			case 0:
			  $yca_output_block = "
			  ctxt_ad_width = 728;
			  ctxt_ad_height = 90;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 1:
			  $yca_output_block = "
			  ctxt_ad_width = 120;
			  ctxt_ad_height = 600;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 2:
			  $yca_output_block = "
			  ctxt_ad_width = 160;
			  ctxt_ad_height = 600;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 3:
			  $yca_output_block = "
			  ctxt_ad_width = 180;
			  ctxt_ad_height = 150;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 4:
			  $yca_output_block = "
			  ctxt_ad_width = 120;
			  ctxt_ad_height = 240;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 5:
			  $yca_output_block = "
			  ctxt_ad_width = 234;
			  ctxt_ad_height = 60;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 6:
			  $yca_output_block = "
			  ctxt_ad_width = 468;
			  ctxt_ad_height = 60;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 7:
			  $yca_output_block = "
			  ctxt_ad_width = 300;
			  ctxt_ad_height = 250;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 8:
			  $yca_output_block = "
			  ctxt_ad_width = 250;
			  ctxt_ad_height = 250;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 9:
			  $yca_output_block = "
			  ctxt_ad_width = 336;
			  ctxt_ad_height = 280;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 10:
			  $yca_output_block = "
			  ctxt_ad_width = 420;
			  ctxt_ad_height = 150;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
			case 11:
			  $yca_output_block = "
			  ctxt_ad_width = 240;
			  ctxt_ad_height = 400;
			  ";
	          $block['content'] = "$yca_output_start $yca_output_block $yca_output_end";
	          break;
	      }
	      return $block;
	  }
}

/*
Utility functions for admin display and value selection
*/
function yca_plugin_type_options() {
	$options = array(
		'business' => t('Business News'),
		'news' => t('News'),
		'lifestyle' => t('Community Agate'),
		'lifestyle' => t('Lifestyle'),
		'employment' => t('Employment'),
		'entertainment' => t('Entertainment'),
		'health' => t('Health'),
		'home_page' => t('Home'),
		'misc' => t('Marketplace'),
		'misc' => t('Mobile'),
		'announcements' => t('Obituaries'),
		'opinion' => t('Opinions'),
		'real_estate' => t('Real Estate'),
		'news' => t('News'),
		'sports' => t('Sports News'),
		'cars' => t('Transportation'),
		'tech' => t('Technology'),
		'blogs_social' => t('UCC'),
		'blogs_social' => t('User Contributed Content'),
		'photos_videos' => t('Video'),
		'misc' => t('Other'),
	);
return $options;
}

function yca_plugin_tier_options() {
	$options = array(
		'1' => t('1'),
		'2' => t('2'),
	);
return $options;
}
